name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  # --- 1. ビルドジョブ (並列実行) ---
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            label: "windows"
            artifact_name: "FileHasher-Windows-x86_64.zip"
          - os: macos-latest
            label: "macos-arm"
            artifact_name: "FileHasher_macOS_aarch64.zip"
          - os: macos-15-intel
            label: "macos-x86"
            artifact_name: "FileHasher_macOS_x86_64.zip"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ">=1.26.0"

      # Windows用のビルド設定
      - name: Setup msys2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@cafece8e6baf9247cf9b1bf95097b0b983cc558d # v2.31.0
        with:
          install: git mingw-w64-x86_64-toolchain zip
          path-type: inherit

      # 各OSでのビルド実行 (ファイル名はOSごとに分ける)
      - name: Build
        run: |
          go install fyne.io/tools/cmd/fyne@latest
          fyne package

      - name: Packing application for Windows
        if: runner.os == 'Windows'
        run: Compress-Archive -Path "File Hasher.exe" -DestinationPath "${{ matrix.artifact_name }}"

      - name: Packing application for non-Windows
        if: runner.os != 'Windows'
        run: zip -r ${{ matrix.artifact_name }} ./File\ Hasher.app

      # 成果物を一時保存 (次のジョブに渡すため)
      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ matrix.label }}
          path: ${{ matrix.artifact_name }}

  # --- 2. リリースジョブ (一括実行) ---
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ./artifacts
          merge-multiple: true # 全ジョブのファイルを1つのフォルダにまとめる

      - name: Create Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: ./artifacts/*
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: "./artifacts/*"
          generateReleaseNotes: true
          # immutableCreate: true
